language: go

go:
  - tip

before_install:
  - sudo apt-get install bzr mercurial git -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - go get gopkg.in/cdnlysis/cdnlysis.v1

script:
  - go build -v ./...

notifications:
  email:
    recipients:
      - piyush@piyushverma.net
    on_success: change
    on_failure: always
